kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: moe
  name: mysql-moe-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: moe
  name: mysql-moe-claim
  labels:
    app: openemis-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi